### ISSUE TITLE
Unmount doesn't switch back to previous set

### ISSUE THREAD

**Issue by philb74** [Rottenbeer/ItemRack#92]
When I mount, the defined set is equipped. 
When I unmount it doesn't switch back to previous set.

It's really weird. 
It doesn't work on my hunter with the raptor, but it works on my warlock with dreadsteed.

Already deleted SavedVariables for my hunter. Didn't help.

**Comment by Rottenbeer** [comment]
Retest with 3.37 please, disble all other addons and move your (complete) WOW folder out of the way.

**Comment by Rottenbeer** [comment]
Did it fix it?

**Comment by philb74** [comment]
I have 3.37 installed. Still didn‘t work, but I have to test it with Folder WTF and Interface removed. 

Everything is working on my warlock, on Hunter it doesn‘t. Swimming scripts f.e. is working well. Can‘t test it on other chars, since no mounts on them at the moment.
Also have to test location based events, if I see a difference.

I will do this this Weekend and let you know.

**Comment by philb74** [comment]
So, I've tested this on a fresh install with no other addons installed.
Unmounting doesn't switch back to previous set.

**Comment by Rottenbeer** [comment]
So it still does not work on the hunter but works on the warlock?
Which item are you trying to equip/unequip? Is it the same item on both characters?
Which mount are you using? Is it the same mount on both characters?
Which server/ character?
Average latency?

**Comment by philb74** [comment]
Yes! This workaround fixed the problem on my hunter. 
So then this is only related to classes/chars which are using items in the projectile/arrow slot.

**Comment by Rottenbeer** [comment]
When you create a new set, is the projectile/arrow slot automatically enabled (unlike the other slots)?

**Comment by philb74** [comment]
When I create a news set, I'm already on an existing set, so I just change the name and save it with new name. Is there any way to create a new set from scratch? Except when having a new install? How could I test? 
What I found out about the projectile/arrow slot also, from time to time it get's lost in the set (if ToggleAll is enabled).

I also found out that I used the plugin in a wrong way. I always used ToggleAll.
Since I only want to change one or two items (carrot f.e.) it makes more sense to only enable related slot. When I enable only related slots, then I have no more problems.

**Comment by Rottenbeer** [comment]
"What I found out about the projectile/arrow slot also, from time to time it get's lost in the set (if ToggleAll is enabled)."
Can you elaborate when this happens or have a closer look?

**Comment by Rottenbeer** [comment]
Can you test this branch please and check if the ammo slot bug is fixed now:
https://github.com/Rottenbeer/ItemRack/commits/fix-ammo-slot-mount
Thanks :D

**Comment by philb74** [comment]
Following problem when addon gets loaded.

Date: 2020-05-30 22:25:23
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ItemRack\ItemRack.lua line 1375:
   attempt to index local 'queue' (a nil value)
Debug:
   ItemRack\ItemRack.lua:1375: UpdateCombatQueue()
   ItemRack\ItemRackButtons.lua:67: InitButtons()
   ItemRack\ItemRack.lua:203: func()
   ItemRack\ItemRack.lua:847: OnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
queue = nil
id = nil
(for index) = 0
(for limit) = 19
(for step) = 1
i = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = "AmmoSlot"
(*temporary) = "Queue"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'queue' (a nil value)"

**Comment by Rottenbeer** [comment]
@philb74 I updated the branch, do you mind to check again please?

**Comment by philb74** [comment]
I see no changes on the branch? did you commit?

**Comment by Rottenbeer** [comment]
@philb74 I force pushed https://github.com/Rottenbeer/ItemRack/commits/fix-ammo-slot-mount

**Comment by philb74** [comment]
@Rottenbeer I tested latest and still get following error.

`Date: 2020-05-31 15:40:27
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ItemRack\ItemRack.lua line 1375:
   attempt to index local 'queue' (a nil value)
Debug:
   ItemRack\ItemRack.lua:1375: UpdateCombatQueue()
   ItemRack\ItemRackButtons.lua:67: InitButtons()
   ItemRack\ItemRack.lua:203: func()
   ItemRack\ItemRack.lua:847: OnUpdate()
   [string "*:OnUpdate"]:1:
      [string "*:OnUpdate"]:1
Locals:
queue = nil
id = nil
(for index) = 0
(for limit) = 19
(for step) = 1
i = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = "AmmoSlot"
(*temporary) = "Queue"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'queue' (a nil value)"`

**Comment by Rottenbeer** [comment]
I guess I need to follow up on this if I have a valid subscription again.

**Comment by philb74** [comment]
Let me know, when I can help you testing.

**Comment by Rottenbeer** [comment]
Thanks :)
I guess it will not be in the near future :/

**Comment by Rottenbeer** [comment]
@philb74 can you retest this on the newest version 3.64 please?

**Comment by hightin** [comment]
Since you are linking to here for the mount set issue. I had to delete the event I had previously and recreate the event to get it to work right. The issue just started happening today and that was the only solution.

**Comment by philb74** [comment]
@Rottenbeer tested it on 3.66. It works well now. Thx!

**Comment by mphilpot22** [comment]
I was having issues with the main set not going back on after the mount set even after the ammo slot workaround. I equipped a tabard and found that it started working (for the most part). There are still times when I get in combat with the mounted set and it doesn't swap back when combat drops and I dismount.
